import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./reset.css";

const godoB = localFont({
  src: "./fonts/GodoB.woff2",
  variable: "--font-godo-b",
  weight: "400",
});

const godoM = localFont({
  src: "./fonts/GodoM.woff2",
  variable: "--font-godo-m",
  weight: "400",
});

const godoL = localFont({
  src: "./fonts/godoRoundedL.woff2",
  variable: "--font-godo-l",
  weight: "400",
});

const godoR = localFont({
  src: "./fonts/godoRoundedR.woff2",
  variable: "--font-godo-r",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${godoB.variable} ${godoM.variable} ${godoL.variable} ${godoR.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
